# Generated by Django 5.1.6 on 2025-03-01 13:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_usuario', models.CharField(max_length=30)),
                ('email_usuario', models.EmailField(max_length=254, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Filmes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=150)),
                ('genero', models.CharField(max_length=40)),
                ('ano', models.CharField(max_length=4)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_avalia_filmes.usuario', to_field='email_usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Avaliacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avaliacao', models.TextField()),
                ('filme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_avalia_filmes.filmes')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_avalia_filmes.usuario', to_field='email_usuario')),
            ],
        ),
    ]
