# Generated by Django 5.1.6 on 2025-03-01 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_avalia_filmes', '0002_filmes_nota_alter_filmes_ano_delete_avaliacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filmes',
            name='ano',
            field=models.CharField(max_length=4),
        ),
    ]
